# Generated by Django 2.1.2 on 2018-10-22 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(default='', max_length=15)),
                ('hora', models.TimeField()),
                ('unidad', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='activa',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Operador'),
        ),
        migrations.AddField(
            model_name='activa',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ruta'),
        ),
    ]
