# Generated by Django 2.1.2 on 2018-10-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activa',
            name='fecha',
        ),
        migrations.AddField(
            model_name='activa',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activa',
            name='gasolina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activa',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activa',
            name='servicio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activa',
            name='hora',
            field=models.CharField(default='', max_length=15),
        ),
    ]
