# Generated by Django 2.1.2 on 2018-10-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181022_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasolina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='activa',
            name='gasolina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Gasolina'),
        ),
    ]
