# Generated by Django 2.1.2 on 2018-10-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181022_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='activa',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
