# Generated by Django 2.1.2 on 2018-10-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_activa_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activa',
            old_name='servicio',
            new_name='observacion',
        ),
    ]
