# Generated by Django 2.1.2 on 2018-10-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181024_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activa',
            new_name='Despacho',
        ),
    ]
